version: "3.1"

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: example
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/var/lib/mongodb/data/
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: example
      ME_CONFIG_MONGODB_ADMINPASSWORD: password

volumes:
  mongo_data:
